# Generated by Django 2.2 on 2019-05-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicetrack',
            name='language',
            field=models.CharField(choices=[('EN', 'English')], default='EN', max_length=2),
        ),
        migrations.AddField(
            model_name='voicetrack',
            name='pitch',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voicetrack',
            name='speed',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voicetrack',
            name='voice',
            field=models.CharField(choices=[('AM', 'Amanda')], default='AM', max_length=2),
        ),
    ]
