# Generated by Django 2.2 on 2019-05-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190519_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voicetrack',
            options={'ordering': ['-created']},
        ),
    ]
