# Generated by Django 2.2 on 2019-05-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190524_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicetrack',
            name='speed',
            field=models.FloatField(default=1),
        ),
    ]
