# Generated by Django 2.2 on 2019-05-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190524_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicetrack',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
