# Generated by Django 2.2 on 2019-05-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_voicetrack_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicetrack',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
    ]
